
import Foundation

class MyAppsData{
    
    static let appNames = ["Data Structures", "C Questions","Clenergize Solar","Clenergize Solar iPhone"]
    static let appIconImages = ["dataStructureIcon","cQuestionsIcon","clenergizeIcon","clenergizeIcon"]
    static let appStatusTitles = ["APP STORE","APP STORE","TESTING","TESTING"]
    static let appCategory = ["Education","Education","Business","Business"]
    static let ratingCount = [8,5,0,0]
    
     static let headerAppNames = ["data Structures", "c Questions","clenergize Solar","clenergize Solar"]
   
    static let appDescription = ["This app will make you learn very important topic that is Data Structure in very impressive manner using numerous steps.\nIt will ease students of I.T. to learn about the Data Structures step by step. Usually we had to first study the Complete Algorithm and then Complete Program which confuse the students about some variables or method. In this we go through each step showing just the corresponding code snippet not the full program.\nThis feature is OFFLINE and can be accessed without any Network Connections.\n*COMPARE: It is used to compare sorting algorithms selecting numbers of less or high range and checking the execution time of the algorithm.\n*QUIZ: Questions and answers are daily updated and provide you great knowledge about this topic.\n*PUSH NEWS: Notifications are the ones which will update you about the daily news of this field.\n*DEFINITIONS: Definitions from various sources.",
                                 
                                 "An Offline app for C questions.\n It contains questions based on C Language.\nFeatures :\n- Topic Wise Questions: Numerous questions on specific topics.\n- Ask Your Doubts and get it cleared within 24 hours.",
                                 
                                 "The Clenergize Solar app is designed carefully to provide the end user with a view to monitor their solar plant and savings in real time. It calculates the productivity and savings data for the solar plant owner with complete transparency.\nWith this app, you can view:\n- energy production of your solar power plant\n- energy consumption of your facility\n- net usage (import and/ export of energy)\n- money savings\n- Carbon Dioxide savings\nThe information above has been translated into an user interface which is fluid and intuitive to use. The mobile app has been crafted by keeping the end user in mind. And therefore, with a single touch, the user can monitor solar plant production vs facility consumption data in day/ month/ year and lifetime view.\nNot only this, but we also equip you with:\n- an option to refer your friends to opt for solar (and in return we share a portion of the benefit with you!!)\n- an alarm view that notifies you of actions that user must take to optimize the solar production on the roof\nIt is a simple, visually rich mobile app that gives the control of the solar plant to the end users.",
                                 
                                 "The Clenergize Solar app is designed carefully to provide the end user with a view to monitor their solar plant and savings in real time. It calculates the productivity and savings data for the solar plant owner with complete transparency.\nWith this app, you can view:\n- energy production of your solar power plant\n- energy consumption of your facility\n- net usage (import and export of energy)\n- money savings\n- Carbon Dioxide savings\nThe information above has been translated into an user interface which is fluid and intuitive to use. The mobile app has been crafted by keeping the end user in mind. And therefore, with a single touch, the user can monitor solar plant production vs facility consumption data in day/ month/ year and lifetime view.\nNot only this, but we also equip you with:\n- an option to refer your friends to opt for solar (and in return we share a portion of the benefit with you!!)\n- an alarm view that notifies you of actions that user must take to optimize the solar production on the roof\nIt is a simple, visually rich mobile app that gives the control of the solar plant to the end users."]
  
    static let codeDescription = ["It is completely developed using Swift Language. It was the first Programming related app on Apple Watch. It engages user with push notifications, I used Parse Cloud for this. Cloud is used to store Quiz questions, notification hub data, feedbacks, errors reports and newsletter signup. Database handling was major challenge for me in this. I developed my own functions to access SQLite Database. I made the programs stored in static database because I wanted that the user can go through it without data packs too. I am working on its new update with Swift and Java Programs along with completely new User interface.","It's is very basic app that I have developed using Objective C but it was a good experience of following the streamline process of uploading the App on the App Store. It also involves use of one third party library of sidebar. It is integrated with Parse Cloud to store values of Report an Error, Newsletter Signup and Feedback screens.","It is completely build using Swift. It involves use of third party Charts Framework to display Bar and Line charts. Major challenge was handling thousands of rows in a SQLite database and calculating the amount of Home usage and Solar Production and putting them on graphs. Currently it is having a static SQLite database but in a few months it will be connected to a dedicated server which will be attached to a solar plant and will be monitoring the usage.","It is completely build using Swift. It involves use of third party Charts Framework to display Bar and Line charts. Major challenge was handling thousands of rows in a SQLite database and calculating the amount of Home usage and Solar Productions and putting them on graphs.  Currently it is having a static SQLite database but in a few months it will be connected to a dedicated server which will be attached to a solar plant and will be monitoring the usage."]
    
    static let appUpdatedOn = ["May 30, 2015 ", "Dec 5, 2014","Apr 2, 2016","Apr 2, 2016"]
    static let appVersion = ["1.0","1.0","3.0 (2.1)","3.0 (2.1)"]
    static let appSize = ["10.8 MB", "3.9 MB","28.5 MB","30.4 MB"]
    static let appCompatibilty = ["iOS 8.3 or later","iOS 8.0 or later","iOS 8.0 or later","iOS 8.0 or later"]
    static let appAppleWatch = ["Yes","No","No","No"]
    static let appCopyright = ["Pawanpreet Singh","Pawanpreet Singh","Clenergize Solar","Clenergize Solar"]
    static let appLinks = ["https://itunes.apple.com/in/app/data-structures/id993677535?mt=8","https://itunes.apple.com/in/app/c-questions/id945388481?mt=8"]
    
    
}